### PR TITLE
fix czam & ads domains

### PR DESCRIPTION
**Pull request by liberodark**
For fix : mon.compteczam.fr is a french online bank

### CODE REVIEW

**Comment by liberodark** [comment]
Commit for https://github.com/AdguardTeam/AdguardDNS/issues/295

**Comment by liberodark** [comment]
Have make update for fix conflicts

**Comment by liberodark** [comment]
Please merge this commit for fix actualy CZAM not work on your dns

**Comment by Alex-302** [comment]
Please write about ads and incorrect blocking to AdguardFilters.

**Pull request closed without merging**
