### PR TITLE
Remove non-ad-related dadi.technology from filter.txt

### PR DESCRIPTION
**Pull request by danwdart**
Please remove dadi.technology from the filter list.
This domain has nothing to do with ads at all.

### CODE REVIEW

**Comment by ameshkov** [comment]
It comes from Easyprivacy filter which purpose is to block known trackers and web analytics.

Could you please explain the purpose of the domain?

**Comment by danwdart** [comment]
I see, it'll have to go from there too then.
It's a web technology stack and has various test domains for open source development of web services. Nothing about it is tracking-related, nor is it anything to do with analytics, it's just services for web publishers.

**Comment by danwdart** [comment]
I've PR'd to them too.

**Comment by ameshkov** [comment]
@danwdart 

> It's a web technology stack and has various test domains for open source development of web services. Nothing about it is tracking-related, nor is it anything to do with analytics, it's just services for web publishers.

Could you please point me out a place where I can read about it?

@Alex-302 could you please take care of it? If this is not a tracking domain, it needs to be excluded from AG filters as well.

**Comment by danwdart** [comment]
Here's the link https://dadi.cloud/en/
It specialises in decentralised web services.
Cheers

**Comment by vozersky** [comment]
Yeah, even if we exclude them now, it's not for long, i guess
up05_bt0dn

**Comment by danwdart** [comment]
Only the actual sites implementing tracking stuff will need blocking, not the tech that makes CMSes.

**Pull request closed without merging**
