### PR TITLE
Fixing official Amazon app https://github.com/AdguardTeam/AdguardFilters/issues/18469

### PR DESCRIPTION
**Pull request by Alex-302**

### CODE REVIEW

**Comment by ameshkov** [comment]
This will unblock A LOT of mobile ads.

**Comment by ameshkov** [comment]
Advise user to unblock it via the

**Comment by Alex-302** [comment]
But we have more than 60 exclusions(a lot of sites) with this domain in Eng filter.

**Comment by Alex-302** [comment]
Ok

**Pull request closed without merging**
